### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Yossiezraa/SubmissionHTML#1]
### Hi Yossi,

Ada beberapa kesalahan nih dalam struktur kodenya

1.Kodemu seperti ini:
![image](https://github.com/Yossiezraa/SubmissionHTML/assets/73971391/9f397dbf-ce5f-4104-a3c5-9117b5f7d99c)
![image](https://github.com/Yossiezraa/SubmissionHTML/assets/73971391/bafda964-cb57-4759-897f-0deaab8af035)
seharusnya struktrunya seperti:
```html
<header>...</header>
<main>
 <div id="content">
  <section id="form">
   <form></form>
  </section>
  <section id="article">
   <article>...</article> 
   <article>...</article> 
   <article>...</article> 
  </section>
  .....
 </div>
 <aside>....</div>
</main>
<footer>...</footer>
```
lalu dibagian `main` kamu masih memisah `article` per section dimana bagusnya kamu mengabungkan kumpulan elemen `article` kedalam satu `section` saja. elemen `aside`mu juga masih didalam `main` dimana seharusnya seperti referensi yang kuberikan diatas. Lalu untuk elemen `form`, bisa kamu pindah kedalam `main` lalu dibuat `section` baru di paling atas didalam `main`

itu aja dari aku, bisa direvisi dan di upload ulang di repository ini ya. Thanks dan jangan lupa komen dibawah kalau sudah

**Comment by not-xygen** [comment]
Submission Approved. Tolong perbaiki yang kurang ya

**Comment by Yossiezraa** [comment]
Selamat malam kak, sudah saya perbaiki dan submit ulang. Terimakasih kak🙏🙏
